# Generated by Django 5.0.4 on 2024-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('exercise', models.CharField(max_length=255)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('goal_time', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('reached', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goals',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='administrativestaff',
            table='administrativestaff',
        ),
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
        migrations.AlterModelTable(
            name='trainers',
            table='trainers',
        ),
    ]
