# Generated by Django 5.0.4 on 2024-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_availabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
            ],
            options={
                'db_table': 'equipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomBookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('booking_start_time', models.DateField()),
                ('booking_end_time', models.DateField()),
                ('admin_staff_id', models.IntegerField()),
            ],
            options={
                'db_table': 'roombookings',
                'managed': False,
            },
        ),
    ]
