# Generated by Django 5.0.4 on 2024-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_fitnessclasses_fitnessclassmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('day', models.CharField(max_length=255)),
                ('trainer_id', models.IntegerField()),
                ('session_start_time', models.TimeField()),
                ('session_end_time', models.TimeField()),
            ],
            options={
                'db_table': 'trainingsessions',
                'managed': False,
            },
        ),
    ]
