# Generated by Django 5.0.4 on 2024-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_trainingsessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('payment_date', models.DateField()),
                ('posted', models.BooleanField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
