from django.urls import path
from . import views

urlpatterns = [
    path('', views.sign_in, name='sign_in'),
    path('login/', views.sign_in, name='sign_in'),
    path('logout/', views.sign_out, name='sign_out'),
    path('register/', views.register, name='register'),
    path('members/<int:id>/', views.member_dashboard, name='members'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('my_profile/update_info', views.update_info, name='update_info'),
    path('my_profile/add_goal', views.add_goal, name='add_goal'),
    path('my_profile/edit_goal', views.edit_goal, name='edit_goal'),
    path('my_profile/delete_goal', views.delete_goal, name='delete_goal'),
    path('my_profile/add_availability', views.add_availability, name='add_availability'),
    path('my_profile/edit_availability', views.edit_availability, name='edit_availability'),
    path('my_profile/delete_availability', views.delete_availability, name='delete_availability'),
    path('my_profile/search_member', views.search_member, name='search_member'),
    path('my_profile/add_equipment', views.add_equipment, name='add_equipment'),
    path('my_profile/edit_equipment', views.edit_equipment, name='edit_equipment'),
    path('my_profile/delete_equipment', views.delete_equipment, name='delete_equipment'),
    path('my_profile/add_booking', views.add_booking, name='add_booking'),
    path('my_profile/edit_booking', views.edit_booking, name='edit_booking'),
    path('my_profile/delete_booking', views.delete_booking, name='delete_booking'),
    path('my_profile/add_session', views.add_session, name='add_session'),
    path('my_profile/edit_session', views.edit_session, name='edit_session'),
    path('my_profile/delete_session', views.delete_session, name='delete_session'),
    path('my_profile/pay_bill', views.pay_bill, name='pay_bill'),
    path('my_profile/authorize_payment/<int:id>/', views.authorize_payment, name='authorize_payment'),
    path('fitness_classes/', views.fitness_classes, name='fitness_classes'),
    path('fitness_classes/join_class/<int:id>/', views.join_fitness_classes, name='join_fitness_classes'),
    path('fitness_classes/leave_class/<int:id>/', views.leave_fitness_classes, name='leave_fitness_classes'),
    path('fitness_classes/add_class', views.add_class, name='add_class'),
    path('fitness_classes/edit_class', views.edit_class, name='edit_class'),
    path('fitness_classes/delete_class', views.delete_class, name='delete_class'),
]